stages:
    # - build
    - publish

# node-repos-build:
#   stage: build
#   image: node:gallium
#   services:
#     - docker:dind
#   script:
#     - npm --prefix ./vscode-webgme-depi install
#     - npm --prefix ./vscode-webgme-depi run compile


vsix-publish:
  stage: publish
  image: node:hydrogen
  services:
    - docker:dind
  only:
    - tags
  before_script:
    - npm install --global @vscode/vsce
  script:
    - npm --prefix ./vscode-webgme-depi install
    - npm --prefix ./vscode-webgme-depi run compile
    - (cd vscode-webgme-depi && vsce package)
  artifacts:
    paths:
      - ./vscode-webgme-depi/*.vsix

docker-publish:
    stage: publish
    tags:
        - ubuntu22
    only:
        - tags
    before_script:
        - docker images -a
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_REGISTRY_PASSWORD
    script:
        - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:1}" ./webgme-depi-components
        - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:1}"
        - docker build -t "$CI_REGISTRY_IMAGE/webgme-depi-vsix:${CI_COMMIT_TAG:1}" .
        - docker push "$CI_REGISTRY_IMAGE/webgme-depi-vsix:${CI_COMMIT_TAG:1}"
    after_script:
        - docker logout $CI_REGISTRY
