version: '3'

services:
  webgme-server:
    image: webgme
    container_name: webgme-server
    restart: always
    environment:
      - NODE_ENV=docker
    ports:
      - 8888:8888
  webgme-monitor:
    image: webgme
    container_name: webgme-monitor
    restart: always
    command: npm run monitor
    environment:
      - NODE_ENV=docker
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    environment:
      - NODE_ENV=docker