const CONSTANTS = {
    DEPI: {
        TOOL_ID: 'webgme',
        PATH_DIVIDER: '/',
    },
    EVENTS: {
        GET_BRANCH_NAME: 'GET_BRANCH_NAME',
        GET_RESOURCE_INFO: 'GET_RESOURCE_INFO',
        SHOW_DEPENDENCY_GRAPH: 'SHOW_DEPENDENCY_GRAPH',
        SHOW_DEPENDANTS_GRAPH: 'SHOW_DEPENDANTS_GRAPH',
        SHOW_BLACKBOARD: 'SHOW_BLACKBOARD',
        REVEAL_RESOURCE: 'REVEAL_RESOURCE',
        GET_DEPENDENCY_GRAPH: 'GET_DEPENDENCY_GRAPH',
        GET_DEPENDANTS_GRAPH: 'GET_DEPENDANTS_GRAPH',
        GET_DEPENDENCIES: 'GET_DEPENDENCIES',
        GET_DEPENDANTS: 'GET_DEPENDANTS',
        ADD_AS_RESOURCE: 'ADD_AS_RESOURCE',
        REMOVE_AS_RESOURCE: 'REMOVE_AS_RESOURCE',
        ADD_DEPENDENCY: 'ADD_DEPENDENCY',
        REMOVE_DEPENDENCY: 'REMOVE_DEPENDENCY',
        ADD_DEPENDANT: 'ADD_DEPENDANT',
        REMOVE_DEPENDANT: 'REMOVE_DEPENDANT',
        // SERVER EVENTS
        DEPI_UPDATED: 'DEPI_UPDATED'
    }
};

export default CONSTANTS;